In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv(r"C:\Users\merli\OneDrive\Desktop\E-commerce Customer Behavior - Sheet1.csv")
df.head()

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,1120.20,14,4.6,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,780.50,11,4.1,False,18,Neutral
2,103,Female,43,Chicago,Bronze,510.75,9,3.4,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,1480.30,19,4.7,False,12,Satisfied
4,105,Male,27,Miami,Silver,720.40,13,4.0,True,55,Unsatisfied

In [4]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [5]:
print(df.columns)

Index(['customer_id', 'gender', 'age', 'city', 'membership_type',
       'total_spend', 'items_purchased', 'average_rating', 'discount_applied',
       'days_since_last_purchase', 'satisfaction_level'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350 entries, 0 to 349
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               350 non-null    int64
 1   gender                    350 non-null    object
 2   age                       350 non-null    int64
 3   city                      350 non-null    object
 4   membership_type           350 non-null    object
 5   total_spend               350 non-null    float64
 6   items_purchased           350 non-null    int64
 7   average_rating            350 non-null    float64
 8   discount_applied          350 non-null    bool
 9   days_since_last_purchase  350 non-null    int64
 10  satisfaction_level        348 non-null    object
dtypes: bool(1), float64(2), int64(4), object(4)
memory usage: 27.8+ KB

In [7]:
df.describe()

,customer_id,age,total_spend,items_purchased,average_rating,days_since_last_purchase
count,350.000000,350.000000,350.000000,350.000000,350.000000,350.000000
mean,275.500000,33.597143,845.381714,12.600000,4.019143,26.588571
std,101.180532,4.870882,362.058695,4.155984,0.580539,13.440813
min,101.000000,26.000000,410.800000,7.000000,3.000000,9.000000
25%,188.250000,30.000000,502.000000,9.000000,3.500000,15.000000
50%,275.500000,32.500000,775.200000,12.000000,4.100000,23.000000
75%,362.750000,37.000000,1160.600000,15.000000,4.500000,38.000000
max,450.000000,43.000000,1520.100000,21.000000,4.900000,63.000000

In [8]:
df.isnull().sum()

customer_id                 0
gender                      0
age                         0
city                        0
membership_type             0
total_spend                 0
items_purchased             0
average_rating              0
discount_applied            0
days_since_last_purchase    0
satisfaction_level          2
dtype: int64

In [9]:
df['satisfaction_level'] = df['satisfaction_level'].fillna(
    df['satisfaction_level'].mode()[0]
)

In [10]:
print(df.isnull().sum())

customer_id                 0
gender                      0
age                         0
city                        0
membership_type             0
total_spend                 0
items_purchased             0
average_rating              0
discount_applied            0
days_since_last_purchase    0
satisfaction_level          0
dtype: int64

In [11]:
labels = ['Young Adult','Adult','Middle-aged','Senior']
df['age_group'] = pd.qcut(df['age'],q=4, labels = labels)

In [12]:
df[['age','age_group']].head(10)

   age    age_group
0   29  Young Adult
1   34  Middle-aged
2   43       Senior
3   30  Young Adult
4   27  Young Adult
5   37  Middle-aged
6   31        Adult
7   35  Middle-aged
8   41       Senior
9   28  Young Adult

In [13]:
print(df['membership_type'].unique())

['Gold' 'Silver' 'Bronze']

In [14]:
frequency_mapping = {
    'Gold': 'Weekly',
    'Silver': 'Bi-weekly',
    'Bronze': 'Monthly'
}

df['purchase_frequency'] = df['membership_type'].map(frequency_mapping)

In [15]:
df[['purchase_frequency','membership_type']].head(10)

  purchase_frequency membership_type
0             Weekly            Gold
1          Bi-weekly          Silver
2            Monthly          Bronze
3             Weekly            Gold
4          Bi-weekly          Silver
5            Monthly          Bronze
6             Weekly            Gold
7          Bi-weekly          Silver
8            Monthly          Bronze
9             Weekly            Gold

In [16]:
df[['discount_applied']].head(10)

   discount_applied
0              True
1             False
2              True
3             False
4              True
5             False
6              True
7             False
8              True
9             False

In [17]:
print(df.columns.tolist())

['customer_id', 'gender', 'age', 'city', 'membership_type', 'total_spend', 'items_purchased', 'average_rating', 'discount_applied', 'days_since_last_purchase', 'satisfaction_level', 'age_group', 'purchase_frequency']

In [18]:
import requests
requests.get("https://pypi.org").status_code

ConnectionError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A314062E40>: Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)"))

In [21]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\merli\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\merli\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\merli\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\merli\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import psycopg2
from sqlalchemy import create_engine

print("Success")

Success

In [23]:
import sys
print(sys.version)

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]

In [24]:
import sys
print(sys.executable)

C:\Users\merli\anaconda3\python.exe

In [25]:
from sqlalchemy import create_engine
username = "postgres"
password = "postgres"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}',")

Data successfully loaded into table 'customer' in database 'customer_behavior',

In [26]:
print(df.columns.tolist())

['customer_id', 'gender', 'age', 'city', 'membership_type', 'total_spend', 'items_purchased', 'average_rating', 'discount_applied', 'days_since_last_purchase', 'satisfaction_level', 'age_group', 'purchase_frequency']

In [27]:
# Save the updated dataset
df.to_csv("Updated_Ecommerce_Customer_Behavior.csv", index=False)

print("Updated dataset saved successfully!")

Updated dataset saved successfully!

In [28]:
print(df.head())
print(df.columns)

   customer_id  gender  age           city membership_type  total_spend  \
0          101  Female   29       New York            Gold      1120.20
1          102    Male   34    Los Angeles          Silver       780.50
2          103  Female   43        Chicago          Bronze       510.75
3          104    Male   30  San Francisco            Gold      1480.30
4          105    Male   27          Miami          Silver       720.40

   items_purchased  average_rating  discount_applied  \
0               14             4.6              True
1               11             4.1             False
2                9             3.4              True
3               19             4.7             False
4               13             4.0              True

   days_since_last_purchase satisfaction_level    age_group purchase_frequency
0                        25          Satisfied  Young Adult             Weekly
1                        18            Neutral  Middle-aged          Bi-weekly
2                        42        Unsatisfied       Senior            Monthly
3                        12          Satisfied  Young Adult             Weekly
4                        55        Unsatisfied  Young Adult          Bi-weekly
Index(['customer_id', 'gender', 'age', 'city', 'membership_type',
       'total_spend', 'items_purchased', 'average_rating', 'discount_applied',
       'days_since_last_purchase', 'satisfaction_level', 'age_group',
       'purchase_frequency'],
      dtype='object')

In [32]:
import os

print(os.getcwd())

C:\Users\merli

In [33]:
import os

print(os.listdir())

['.anaconda', '.aws', '.conda', '.condarc', '.continuum', '.copilot', '.gitconfig', '.ipynb_checkpoints', '.ipython', '.jupyter', '.matplotlib', '.node_repl_history', '.python_history', '.vscode', '.vscode-shared', 'anaconda3', 'AppData', 'Application Data', 'cleaned_influencer_campaign_dataset.csv', 'Contacts', 'Cookies', 'customer behaviour.ipynb', 'Documents', 'Downloads', 'EDA bookanalysis.ipynb', 'Favorites', 'influencer_campaign_analysis.ipynb.ipynb', 'internship task7', 'Links', 'Local Settings', 'main.py', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{a1afb274-060f-11f0-adb3-a8e291e3b173}.TM.blf', 'NTUSER.DAT{a1afb274-060f-11f0-adb3-a8e291e3b173}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{a1afb274-060f-11f0-adb3-a8e291e3b173}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'OneDrive', 'portfolio.txt', 'PrintHood', 'README.md', 'Recent', 'reviews.csv', 'Saved Games', 'Searches', 'segmented_influencer_dataset.csv', 'SendTo', 'SentimentAnalysis.ipynb', 'Start Menu', 'task 07.ipynb', 'Templates', 'Untitled-1.html', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled2.ipynb', 'Updated_Ecommerce_Customer_Behavior.csv', 'Updated_Ecommerce_Customer_Behavior.xlsx', 'Videos', 'web_scraping', 'web_scraping-codealpha']